trigger:
- main

pool:
vmImage: 'ubuntu-latest'

steps:
-	task: NodeTool@0 inputs:
versionSpec: '18.x' displayName: 'Instalar Node.js'

-	script: | npm install
npm run build
displayName: 'Instalar dependencias y construir app'

-	task: AzureWebApp@1 inputs:
azureSubscription: '<Nombre de la conexiÃ³n de servicio>' appType: 'webAppLinux'
appName: '<Nombre de tu Web App>'
package: '$(System.DefaultWorkingDirectory)/*/.zip'
